In [4]:
import pandas as pd

In [5]:
s=pd.Series([1,2,3,4,5,6])
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [6]:
print(s[0]) #acces the first element
print(s[1:4])

1
1    2
2    3
3    4
dtype: int64

In [7]:
# custom index
s=pd.Series([1,2,3], index=["a","b","c"])
print(s)

a    1
b    2
c    3
dtype: int64

# Series from dictionary

In [8]:
data = {"Math":90, "physics":85, "chemistory":88}
marks=pd.Series(data)
print(marks)

Math          90
physics       85
chemistory    88
dtype: int64

In [9]:
data={
    "Name": ["Amam", "Krish", "karam"],
    "Age": [16,15,17],
    "marks":[55,68,49]}

print(data)

{'Name': ['Amam', 'Krish', 'karam'], 'Age': [16, 15, 17], 'marks': [55, 68, 49]}

In [10]:
type(data)

dict

In [11]:
marks=pd.DataFrame(data) #pandas automaticlly adds a default index, this is called range index 
print(marks)

    Name  Age  marks
0   Amam   16     55
1  Krish   15     68
2  karam   17     49

In [12]:
#we can also add custom index
marks=pd.DataFrame(
    data,
    index=["Student1","student2","student3"]
)
print(marks)

           Name  Age  marks
Student1   Amam   16     55
student2  Krish   15     68
student3  karam   17     49

In [13]:
marks.set_index("Name",inplace=True)#if you are setting thid as true it means you are changing the original object itself if false that means one new data set is created

# dataframe

In [14]:
df=pd.DataFrame({
    "Name": ["Aman", "Krish", "karam"],
    "Age": [16,15,17],
    "marks":[55,68,49]
})
print(df)

    Name  Age  marks
0   Aman   16     55
1  Krish   15     68
2  karam   17     49

In [15]:
# df.head()
df.tail()

    Name  Age  marks
0   Aman   16     55
1  Krish   15     68
2  karam   17     49

In [16]:
df.shape

(3, 3)

In [17]:
df.columns

Index(['Name', 'Age', 'marks'], dtype='object')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [19]:
len(df)#print the no of rows

3

In [20]:
df.describe() #discriptive data

        Age      marks
count   3.0   3.000000
mean   16.0  57.333333
std     1.0   9.712535
min    15.0  49.000000
25%    15.5  52.000000
50%    16.0  55.000000
75%    16.5  61.500000
max    17.0  68.000000

In [21]:
df["Name"] #selecting the data

0     Aman
1    Krish
2    karam
Name: Name, dtype: object

In [22]:
df[["Name","marks"]]

    Name  marks
0   Aman     55
1  Krish     68
2  karam     49

# filtering in pandas

In [23]:
df[df["marks"]>50]

    Name  Age  marks
0   Aman   16     55
1  Krish   15     68

In [24]:
df[(df["Age"]>15) & (df["marks"]>50)]

   Name  Age  marks
0  Aman   16     55

In [25]:
df.sort_values("marks")
df

    Name  Age  marks
0   Aman   16     55
1  Krish   15     68
2  karam   17     49

In [26]:
df.sort_values("marks",ascending=False)

    Name  Age  marks
1  Krish   15     68
0   Aman   16     55
2  karam   17     49

In [27]:
df["Age"].value_counts() #to check the count of the same element

Age
16    1
15    1
17    1
Name: count, dtype: int64

In [28]:
# handling missing value
df= pd.DataFrame({
    "Name": ["Aman", "Krish",None, "karam"],
    "Age": [16,None,15,17],
    "marks":[55,None,68,49]
})
df

    Name   Age  marks
0   Aman  16.0   55.0
1  Krish   NaN    NaN
2   None  15.0   68.0
3  karam  17.0   49.0

In [29]:
df.isnull()

    Name    Age  marks
0  False  False  False
1  False   True   True
2   True  False  False
3  False  False  False

In [30]:
df.isnull().sum()

Name     1
Age      1
marks    1
dtype: int64

In [31]:
cleaned_data=df.dropna() #drop rows null values 
cleaned_data

    Name   Age  marks
0   Aman  16.0   55.0
3  karam  17.0   49.0

In [ ]:
#exercise
df=pd.DataFrame({
    "Name": ["Aman", "Sourav", "karan", "Shubham", "Abhishek", None, "Sameer"],
    "Age": [22,23,None,22,25,24,26],
    "marks":[85,None,88,90,56,72,None],
    "Subject": ["Math", "Physics", "Math", "Chemistry", "Math", "Physics", "Chemistry"]})

df

       Name   Age  marks    Subject
0      Aman  22.0   85.0       Math
1    Sourav  23.0    NaN    Physics
2     karan   NaN   88.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math
5      None  24.0   72.0    Physics
6    Sameer  26.0    NaN  Chemistry

In [36]:
df.dropna

<bound method DataFrame.dropna of        Name   Age  marks    Subject
0      Aman  22.0   85.0       Math
1    Sourav  23.0    NaN    Physics
2     karan   NaN   88.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math
5      None  24.0   72.0    Physics
6    Sameer  26.0    NaN  Chemistry>

In [35]:
df.shape

(7, 4)

In [41]:
type(df)
df.dtypes

Name        object
Age        float64
marks      float64
Subject     object
dtype: object

In [43]:
df["marks"].min()

56.0

In [44]:
df["marks"].max()

90.0

In [45]:
df["marks"].mean()

np.float64(78.2)

In [46]:
df[["Name","marks"]]

       Name  marks
0      Aman   85.0
1    Sourav    NaN
2     karan   88.0
3   Shubham   90.0
4  Abhishek   56.0
5      None   72.0
6    Sameer    NaN

In [47]:
df[(df["marks"]>80)]

      Name   Age  marks    Subject
0     Aman  22.0   85.0       Math
2    karan   NaN   88.0       Math
3  Shubham  22.0   90.0  Chemistry

In [48]:
df[(df["marks"]>80) & (df["Age"]>22)]

Empty DataFrame
Columns: [Name, Age, marks, Subject]
Index: []

In [49]:
df["Subject"].value_counts()

Subject
Math         3
Physics      2
Chemistry    2
Name: count, dtype: int64

In [54]:
df.sort_values(by="marks", ascending=False)#.head(2)

       Name   Age  marks    Subject
3   Shubham  22.0   90.0  Chemistry
2     karan   NaN   88.0       Math
0      Aman  22.0   85.0       Math
5      None  24.0   72.0    Physics
4  Abhishek  25.0   56.0       Math
1    Sourav  23.0    NaN    Physics
6    Sameer  26.0    NaN  Chemistry

In [55]:
df["marks"].nlargest(2)

3    90.0
2    88.0
Name: marks, dtype: float64

In [56]:
df.isna().sum()

Name       1
Age        1
marks      2
Subject    0
dtype: int64

In [57]:
df[df["marks"].isna()]

     Name   Age  marks    Subject
1  Sourav  23.0    NaN    Physics
6  Sameer  26.0    NaN  Chemistry

In [58]:
cleared_df = df.dropna()
cleared_df

       Name   Age  marks    Subject
0      Aman  22.0   85.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math

In [59]:
cleared_df.shape

(3, 4)

In [ ]:
#look at the marks column in your output why are the values float instead of integers
#because every column is nan ba default and np.nan is float type

2.what is the risk of using inplace=true when dropping missing values

# GroupBy in pandas

In [60]:
df=pd.DataFrame({
    "Name": ["Aman", "Sourav", "karan", "Shubham", "Abhishek", None, "Sameer"],
    "Age": [22,23,None,22,25,24,26],
    "marks":[85,None,88,90,56,72,None],
    "Subject": ["Math", "Physics", "Math", "Chemistry", "Math", "Physics", "Chemistry"]})

df

       Name   Age  marks    Subject
0      Aman  22.0   85.0       Math
1    Sourav  23.0    NaN    Physics
2     karan   NaN   88.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math
5      None  24.0   72.0    Physics
6    Sameer  26.0    NaN  Chemistry

In [ ]:
df.groupby('Subject')['marks'].mean() #mean of  the marks of each subject

Subject
Chemistry    90.000000
Math         76.333333
Physics      72.000000
Name: marks, dtype: float64

In [63]:
df.groupby('Subject')['Name'].count() #count students per subject

Subject
Chemistry    2
Math         3
Physics      1
Name: Name, dtype: int64

In [64]:
df.groupby('Subject').size() #this will include the  missing values in the count also

Subject
Chemistry    2
Math         3
Physics      2
dtype: int64

In [66]:
#multiple aggregation
df.groupby('Subject')['marks'].agg(['mean','max','min','count'])

                mean   max   min  count
Subject
Chemistry  90.000000  90.0  90.0      1
Math       76.333333  88.0  56.0      3
Physics    72.000000  72.0  72.0      1

In [71]:
#Group by multiple columns
df.groupby(['Subject','Age'])['marks'].mean()

Subject    Age
Chemistry  22.0    90.0
           26.0     NaN
Math       22.0    85.0
           25.0    56.0
Physics    23.0     NaN
           24.0    72.0
Name: marks, dtype: float64